version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/totem_app_admin
    env_file: .env
    ports:
      - "8008:8008"
    image: app:totem_app_admin
    environment:
     - TZ=America/Manaus
    container_name: totem_app_admin
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8008"
    extra_hosts:
     - "host.docker.internal:host-gateway"